version: '3.8'
services:
  database:
    image: postgres:14.1-alpine
    container_name: database
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - ../.env
    ports:
      - '5432:5432'

  api:
    build :
      context: ../
      dockerfile: Dockerfile.prod
    ports : 
      - "8000:8000"
    env_file:
      - ../.env
    volumes: 
      - ../api/:/src
    depends_on:
      - database
    links:
      - database:database


volumes:
  database:

