#!/bin/bash

source ./scripts/variables

case $1 in
    makemigrations)
        sudo docker-compose -f $compose_local run api python manage.py makemigrations
    ;;
    migrate)
        sudo docker-compose -f $compose_local run api python manage.py migrate
    ;;
*)
exit
;;
esac

        